{% set name = "djangocms-history" %}
{% set version = "2.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/djangocms-history-{{ version }}.tar.gz
  sha256: 1e6f7e7bc440c89c6a56966d2f423984e194ff5b02cd6bc7692d1d1a129ca964

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django-cms >=3.7

test:
  imports:
    - djangocms_history
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/django-cms/djangocms-history
  summary: Adds undo/redo functionality to django CMS
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
